[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "server/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server"
  status = 200